exclude: "^(?!odoo/)|.pot$|.po$"
repos:
- repo: local
  rev: 3.9.2
  hooks:
    - id: flake8
      name: flake8
      additional_dependencies: [ "flake8-bugbear==21.4.3" ]
- repo: local
  rev: v2.5.3
  hooks:
  - id: pylint
    name: pylint odoo
    # check only specific Odoo addons
    files: \.py$
    types: ['file', 'python']   # to not check .csv and .conf files
    args: []
    additional_dependencies: [
        "pylint-odoo == 3.7.1",
    ]